
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION_PLACEHOLDER>
        LoadBalancerInfo:
          ContainerName: karrio
          ContainerPort: 3000
