# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0


version: '3.8'

services:
  db:
    image: postgres:14
    container_name: karrio-db
    environment:
      POSTGRES_DB: karrio
      POSTGRES_USER: karrio
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./apps/server
    container_name: karrio-server
    environment:
      - DATABASE_URL=postgresql://karrio:secret@db:5432/karrio
    ports:
      - "5002:8000"
    depends_on:
      - db

  dashboard:
    build:
      context: ./apps/dashboard
    container_name: karrio-dashboard
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5002
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data:
