# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0


version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - user-service
      - product-service

networks:
  app-network:
