name: Copywrite

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "oaa_dons"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "new_work_place"

jobs:
  copywrite:
    name: Run Header Copyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Copywrite
        id: install
        uses: hashicorp/setup-copywrite@v1.0.0

      - name: Output Installed Copywrite Version
        run: echo "Installed Copywrite CLI ${{ steps.install.outputs.version }}"

      - name: Run Copywrite Header Compliance
        run: copywrite headers --plan


