name: Deploy via CodeDeploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ECR"]
    types:
      - completed

jobs:
  codedeploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create code ZIP for main
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        run: |
          aws deploy push \
            --application-name frontend-deploy \
            --description "This is a revision for the application mynodeapp" \
            --ignore-hidden-files \
            --s3-location s3://mynodeapplicationbucket/code.zip \
            --source .

      - name: Deploy main branch
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        run: |
          aws deploy create-deployment \
            --application-name frontend-deploy \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --deployment-group-name frontend-deploy-group \
            --revision '{
              "revisionType": "S3",
              "s3Location": {
                "bucket": "mynodeapplicationbucket",
                "key": "code.zip",
                "bundleType": "zip"
              }
            }'
