name: Blue_Green_Deploy_CodeDeployToECS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Generate ECS task definition
        run: |
          cat <<EOF > frontend-task-def.json
          {
            "family": "frontend-task",
            "executionRoleArn": "arn:aws:iam::537124950459:role/CodeDeploy-Service-role",
            "networkMode": "bridge",
            "containerDefinitions": [
              {
                "name": "web",
                "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/web-ecr-repository:latest",
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                  }
                ],
                "essential": true,
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/frontend",
                    "awslogs-region": "${{ secrets.AWS_REGION }}",
                    "awslogs-stream-prefix": "ecs"
                  }
                }
              }
            ],
            "requiresCompatibilities": ["EC2"],
            "cpu": "512",
            "memory": "1024"
          }
          EOF

      - name: Zip deployment bundle
        run: |
          mkdir bundle
          cp frontend-task-def.json appspec.yaml bundle/
          cd bundle && zip ../code-deploy.zip * && cd ..

      - name: Upload revision to S3
        run: |
          aws s3 cp code-deploy.zip s3://mynodeapplicationbucket/code.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name frontend-deploy \
            --deployment-group-name frontend-deploy-group \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --revision "revisionType=S3,s3Location={bucket=mynodeapplicationbucket,key=code.zip,bundleType=zip}"